"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.defaults = {
    // Server
    host: "127.0.0.1",
    serverPort: "57110",
    protocol: "udp",
    debug: false,
    echo: true,
    // scsynth
    numPrivateAudioBusChannels: 112,
    numAudioBusChannels: 128,
    numControlBusChannels: 4096,
    numInputBusChannels: 2,
    numOutputBusChannels: 2,
    numBuffers: 1026,
    maxNodes: 1024,
    maxSynthDefs: 1024,
    blockSize: 64,
    hardwareBufferSize: null,
    memSize: 8192,
    numRGens: 64,
    numWireBufs: 64,
    sampleRate: 44000,
    loadDefs: true,
    inputStreamsEnabled: null,
    outputStreamsEnabled: null,
    device: null,
    verbosity: 0,
    restrictedPath: null,
    ugenPluginsPath: null,
    initialNodeID: 1000,
    remoteControlVolume: false,
    memoryLocking: false,
    threads: false,
    useSystemClock: false,
    zeroConf: false,
};
//# sourceMappingURL=options.js.map